project_id = "ntailkcafltxoczsrlpz"

[functions.send-push-notification]
verify_jwt = false

[functions.geocode-location]
verify_jwt = false

[functions.reverse-geocode]
verify_jwt = false

[functions.search-locations]
verify_jwt = false

[functions.calculate-trip-fare]
verify_jwt = false

[functions.get-weekly-fare]
verify_jwt = false

[functions.monime]
verify_jwt = false

[functions.dispatch]
verify_jwt = false